// Generated by CoffeeScript 1.6.2
var $img, $sections, $window, docHeight, numberSections;

docHeight = $(window).height();

$sections = $("section");

$sections.css("min-height", docHeight);

$window = $(window);

$img = $('#pinned-image-container');

$img.html($('section').first().find('.section-graphic').html());

$('section').first().find('p').css('bottom', 'auto');

numberSections = function() {
  return $sections.each(function(i, el) {
    return $(el).attr('id', i);
  });
};

numberSections();

$(document).ready(function() {
  var scrollorama = $.scrollorama({
    blocks: '.section-panel'
  });
  return scrollorama.onBlockChange(function() {
    return _.debounce($img.fadeOut(200, function() {
      return $img.html($('#' + scrollorama.blockIndex).find('.section-graphic').html()).fadeIn(500);
    }));
  });
});
