// Generated by CoffeeScript 1.6.2
d3.csv('../data/section1.csv', function(err, _json) {
  return $.each(_json, function(key, data) {
    return $('#section1 #' + data.State).css('fill', function() {
      if (data['Judicial Election?'] === 'Y') {
        return 'red';
      }
    });
  });
});

d3.csv('../data/section2.csv', function(err, _json) {
  console.log('json', _json);
  return $.each(_json, function(key, data) {
    console.log('k', key, 'd', data, data.State);
    return $('#section2 #' + data.State).css('fill', function() {
      if (data['Fail?'] === 'Y') {
        return 'red';
      }
    });
  });
});
